M48
; DRILL file {KiCad 9.0.5-9.0.5~ubuntu24.04.1} date 2025-12-28T13:44:31+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-28T13:44:31+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-9.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X198.1Y-38.6
X198.1Y-111.4
X250.9Y-38.6
X250.9Y-111.3
M30
